Larger the Icons for Header and Footer Section(Responsive)
nirmalyax/React-folio pull request #17
Opened 2023-10-14 20:16 UTC by DeepRahangdale

Made Appropriate Changes in the Header and The Footer Section of the Project.

2023-10-14 22:12 UTC, nirmalyax requested changes
### _Header section_
- The icons are too large for the Header section.
- There must be a porper difference in the heading and sub-heading.
- Make the icons a bit small  and maintain the padding ratio on both sides of the heading.

### _Footer section_
- The color scheme `white over light-blue` is not giving a good UI experince.

2023-10-14 22:48 UTC, DeepRahangdale commented
okh will look after it.

2023-10-16 19:56 UTC, DeepRahangdale commented
@nirmalyax  I have updated the Header and footer section have a look now!!

2023-10-21 07:30 UTC, nirmalyax approved these changes

2023-10-21 07:30 UTC, merged